import io
import zipfile
from app.compiler.parser import parse_yaml_workflow
from app.compiler.validator import validate_workflow
from app.compiler.langgraph_gen import (
    generate_langgraph, 
    generate_fastapi, 
    generate_dockerfile, 
    generate_docker_compose, 
    generate_requirements
)

def export_project_zip(yaml_content: str) -> bytes:
    workflow = parse_yaml_workflow(yaml_content)
    validate_workflow(workflow)
    
    graph_code = generate_langgraph(workflow)
    main_code = generate_fastapi(workflow)
    dockerfile_code = generate_dockerfile(workflow)
    docker_compose_code = generate_docker_compose(workflow)
    reqs_code = generate_requirements(workflow)
    
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("app/__init__.py", "")
        zf.writestr("app/graph.py", graph_code)
        zf.writestr("app/main.py", main_code)
        zf.writestr("app/state.py", "# State definition (merged into graph.py for now)\n")
        zf.writestr("app/config.py", "from pydantic_settings import BaseSettings\nclass Settings(BaseSettings):\n    pass\nsettings = Settings()\n")
        zf.writestr("agents/__init__.py", "")
        zf.writestr("prompts/__init__.py", "")
        zf.writestr("tools/__init__.py", "")
        zf.writestr("Dockerfile", dockerfile_code)
        zf.writestr("docker-compose.yml", docker_compose_code)
        zf.writestr("requirements.txt", reqs_code)
        
        # Inject user API keys
        env_content = "\n".join([f"{k}={v}" for k, v in workflow.api_keys.items()])
        if not env_content:
            env_content = "OPENAI_API_KEY=\nANTHROPIC_API_KEY=\n"
        zf.writestr(".env.example", env_content)
        
        zf.writestr("README.md", f"# {workflow.id}\nGenerated by AgentForge.\n")
        
    return zip_buffer.getvalue()
